### PR TITLE
Add some references and explanations to Lua scripting docs

### PR DESCRIPTION
**Pull request by FichteFoll**
See also https://github.com/hexchat/hexchat/issues/1824.

### CODE REVIEW

**Comment by TingPing** [comment]
Should mention that this is specific to the Windows install

**Comment by FichteFoll** [comment]
Everything? Why?

**Comment by TingPing** [comment]
Because on other platforms we don't know what version of Lua you use, we don't know what Lua libraries are installed, etc.

**Comment by FichteFoll** [comment]
Ah yeah, makes sense. Wonder whether I should just plugi a "warning" block in there.

I also wonder whether I should move the section down since it being only relevant for one platform makes it certainly less important than the main API.

**Comment by TingPing** [comment]
Well you can shorten it up a bit, for example you don't need to mention that `DLUAJIT_ENABLE_LUA52COMPAT` isn't used, the lgi example can be removed since you point to upstreams docs, etc.

**Comment by FichteFoll** [comment]
I tried moving the section to the end of the page, but it seemed helplessly lost behind the giant API section. Mentioning `DLUAJIT_ENABLE_LUA52COMPAT ` was only 4 words, but most likley won't matter to anyone.

**Comment by TingPing** [comment]
I don't think it is a problem near the top.

**Pull request merged**
