### PR TITLE
Add some initial (incomplete) documentation about colors

### PR DESCRIPTION
**Pull request by JohnVillalovos**
Add some initial documentation about colors. Hopefully this will be
useful for people who are trying to customize their colors and/or
working on themes.

Also provides a template for future people to add additional
documentation on what all the various Text Events are for.

Change-Id: Icc2f2ccf77158d9d24adbdbdd19fc832880d5759

### CODE REVIEW

**Comment by TingPing** [comment]
These docs are meant for end users, the on-disk format of files is not really a concern for users. All information anybody cares about when making a theme is provided mentioned already and can be customized within the clients UI.

**Comment by JohnVillalovos** [comment]
I'm an end-user :)  And I care about this information. The documentation at the moment is very sparse when trying to figure out how to make changes to the appearance. The Text Events box is this giant list of entries with names that in my opinion aren't intuitive for what they affect.

Thus the goal of this patch is to help people like me, and people like my co-workers who are also trying to change the appearance of the colors and get confused on what values to change.

I feel I am part of the group "anybody" and I would greatly care for more information on how to make a theme :)

Thanks,
John

**Comment by TingPing** [comment]
>  The Text Events box is this giant list of entries with names that in my opinion aren't intuitive for what they affect

They largely seem very clear to me, of course they require knowledge of IRC but that will always be the case.

> I feel I am part of the group "anybody" and I would greatly care for more information on how to make a theme :)

That is fine but the format of config files is not relevant to making themes, *colors.conf* is not human readable and *pevents.conf* is a worse interface than the settings window which *does* include descriptions already for the variables.

**Comment by JohnVillalovos** [comment]
Ultimately this is not my project and not my decision to make.

I have been using IRC for over 15 years now. And for the most part things are not clear to me. I guess the decision to be made is what is the purpose of the documentation. Is it aimed at the developers of the program or people who are not familiar with the program. I know what I would choose.

I am not that familiar with the program and do not understand the settings as can be seen in that I only came up with descriptions for two items :)

The pevents.conf section could just as easily be called Text Events. Just something to help explain what all the entries mean.

I just wanted to add information that I would like to have seen when I first tried to use Hexchat. And then the 2nd, 3rd, and more times I go and re-install and I don't remember which setting it was that I had changed before.

Thanks,
John

**Comment by TingPing** [comment]
>  Is it aimed at the developers of the program or people who are not familiar with the program.

Stop making such a silly statement. My point is you are talking about config file formats, not anything useful.

> The pevents.conf section could just as easily be called Text Events. Just something to help explain what all the entries mean.

If you actually do that I will consider accepting it, but I do believe this is the wrong place for it, the settings window already has descriptions and if people need more they should go there, not here.

Anyway you currently have nothing in that section so this PR doesn't add anything.

**Pull request closed without merging**
